title : RIMEL Book
tagline: Reverse
email: MireilleBF@gmail.com
author :
  name : Mireille Blay-Fornarino
  email : blay@unice.fr
description: >- # this means to ignore newlines until "baseurl:"
  Course about Reverse Engineering
  
permalink: /:year/:month/:day/:title.html
redirects: yes
exclude: [ _posts/source/, _posts/_private/, _posts/POUB, vendor ]

plugins::
  - jekyll-pandoc
  - jemoji

#markdown: pandoc

highlighter: rouge
source: .
lsi: True

pageviews: yes    ## toggle on sidebar pageviews 
gitstamps: yes
repo: https://github.com/RIMEL-UCA/RIMEL-UCA.github.io # used in linking history

baseurl: '/'




#markdown: redcarpet
#redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
