services:
  analysis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rimel-analysis
    volumes:
      - ./:/app
      - ./3-activite-contributeurs/outputs:/outputs
    working_dir: /app
    command: bash -c "echo 'Container ready'"
    networks:
      - sonar-net
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-server
    ports:
      - "9000:9000"
    networks:
      - sonar-net
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

networks:
  sonar-net:
    driver: bridge
