title = "stacked-regressions-top-4-on-leaderboard"

[metadata]
path = "stacked-regressions-top-4-on-leaderboard.ipynb"
source = "https://www.kaggle.com/code/serigne/stacked-regressions-top-4-on-leaderboard"
author = "serigne"
date = "2017-12-16"
